# Generated by Django 4.0.5 on 2022-07-02 22:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_posts_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='reader',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
